@authUrl = {{$dotenv CPI_API_TOKEN_URL}}
@cloudUrl = {{$dotenv CPI_API_URL}}
@clientID = {{$dotenv CPI_API_CLIENT}}
@clientSecret = {{$dotenv CPI_API_SECRET}}

### get oauth
# @name getOauthToken
POST {{authUrl}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{clientID}}
&client_secret={{clientSecret}}


### get $metadata
@oauth_token = {{getOauthToken.response.body.access_token}}
GET {{cloudUrl}}/api/v1/$metadata
Authorization: Bearer {{oauth_token}}


### get packages
GET {{cloudUrl}}/api/v1/IntegrationPackages?$format=json
Authorization: Bearer {{oauth_token}}


### get csrf
# @name getToken
HEAD {{cloudUrl}}/api/v1
Authorization: Bearer {{oauth_token}}
X-CSRF-Token: fetch

###
@csrf_token = {{getToken.response.headers.x-csrf-token}}

### Vars
@PKG = TMP
@IFLOW = Iflow

### create package
POST {{cloudUrl}}/api/v1/IntegrationPackages
Content-Type: application/json
Authorization: Bearer {{oauth_token}}
X-CSRF-Token: {{csrf_token}}

{
    "Id": "{{PKG}}",
    "Name": "Test",
    "ShortText": "Test package"
}


### create iflow
POST {{cloudUrl}}/api/v1/IntegrationDesigntimeArtifacts
Content-Type: application/json
Authorization: Bearer {{oauth_token}}
X-CSRF-Token: {{csrf_token}}

{
    "Id": "{{IFLOW}}",
    "Name": "Test iflow",
    "PackageId": "{{PKG}}"
}


### get package artifacts
@oauth_token = {{getOauthToken.response.body.access_token}}
GET {{cloudUrl}}/api/v1/IntegrationPackages('{{PKG}}')/IntegrationDesigntimeArtifacts?$format=json
Authorization: Bearer {{oauth_token}}


### download zip
GET {{cloudUrl}}/api/v1/IntegrationDesigntimeArtifacts(Id='{{IFLOW}}',Version='1.0.0')/$value
Accept: application/zip
Authorization: Bearer {{oauth_token}}

### delete package
DELETE {{cloudUrl}}/api/v1/IntegrationPackages('{{PKG}}')
Authorization: Bearer {{oauth_token}}


### Operations list artifacts (runtime)
@cmdList = com.sap.it.op.tmn.commands.dashboard.webui.IntegrationComponentsListCommand
GET {{cloudUrl}}/Operations/{{cmdList}}
Authorization: Bearer {{oauth_token}}


### Operations download
@cmdDownload = com.sap.it.nm.commands.deploy.DownloadContentCommand
@id = 
GET {{cloudUrl}}/Operations/{{cmdDownload}}?artifactIds={{id}}
Authorization: Bearer {{oauth_token}}
